### PR TITLE
temp fix for quitting on mac

### PR DESCRIPTION
**Pull request by lukasoppermann**
This does not work, as the quit event from cmd + q and the menu action for close is blocked. 

If you want this working you would need to distinguish between clicking the (x) on a window (and maybe add the cmd + w shortcut for this) and between closing the app `role:close`.

Reverting your change makes the app close on cmd + q, the menu item and the x on the window, which is better than the behaviour before. Especially since opening a new window results in the bug #4.

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey @claudemuller, will you merge this, or fix it in a real way?

**Comment by claudemuller** [comment]
Hey Lukas

Unfortunately I couldn't merge your request as it still contains remnants of the purged files. I have however implemented your temporary solution for the quitting on OSX bug.

Please confirm that it works. I'll work on this soon.

**Comment by lukasoppermann** [comment]
I think it works. However when I follow the steps to build the app it creates an app that only says `loading …` quitting it works fine however.

**Comment by claudemuller** [comment]
OK kewl, thanks. Yeah I did some work this morning around why the actual FTP side of things isn't working. I've reached a solution, just need to implement it.

Keep yer eyes peeled :)

**Pull request closed without merging**
