### PR TITLE
Add Sftp connections

### PR DESCRIPTION
**Pull request by Alustrat**
Hi, this is just a suggestion to allow sftp connections and answer to #7 

Here is just what I did :
Split functions in two, FTP and SFTP and choose the right one for the connection required.
Add privateKey uri and passphrase fields to the connection from.

### CODE REVIEW

**Review by claudemuller — COMMENTED** [review]
Hi Alustrat

While I see you've done a lot of work on this, which is greatly appreciated, I can't seem to get Alustrat/ffftp the sftp branch working. It says that it connects to an SFTP server, but does not show a directory listing?

**Comment by Alustrat** [comment]
Hi !

Sorry, I'm looking at this today. I just saw I forgot things, so I will fix that this evening.

Thank you for your feedback. I know this is not the cleanest build to add sftp but I hope that it will help you with your project.

**Comment by ghost** [comment]
Please merge 🥇 👍

**Comment by ghost** [comment]
@mitchas, @Alustrat and @claudemuller  👎 SFTP is really needed in this application would be really nice if you can add this please.

**Pull request closed without merging**
